### ISSUE TITLE
Latest Supported Version of Memcached and Redis on FAQ

### ISSUE THREAD

**Issue by sumodirjo** [awsdocs/amazon-elasticache-docs#15]
Elasticache FAQ https://aws.amazon.com/elasticache/faqs/ mention 

- Memcached 1.5.10 as latest supported. Currently Memcached 1.5.16 already supported by ElastiCache.
- Redis 5.0.3 as latest supported. Currently Redis 5.0.4 is already supported by ElastiCache.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
