### ISSUE TITLE
add separate examples for cluster enabled/disabled

### ISSUE THREAD

**Issue by krishna81m** [awsdocs/amazon-elasticache-docs#18]
You should add better/separate AWS CLI examples for describe-cache-clusters and describe-replication-groups _for differentiating cluster mode disabled and enabled_. The examples only describe cluster mode disabled, what about cluster mode enabled, how do you find the primary replica node endpoints?

And, why aren't there separate DNS names for write masters and slaves, some times you don't want reads coming from read slaves.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
