### ISSUE TITLE
Use Primary instead of Primary??

### ISSUE THREAD

**Issue by RichieRunner** [awsdocs/amazon-elasticache-docs#25]
> For write activity, we recommend that your applications connect to the **primary endpoint** instead of connecting directly to the **primary**

What is meant here? I'm assuming one of it isn't primary. 

https://github.com/awsdocs/amazon-elasticache-docs/blob/master/doc_source/redis/Endpoints.md

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
