### ISSUE TITLE
Doc page for Outposts doesn't indicate ElastiCache back end EBS consumption

### ISSUE THREAD

**Issue by adam-imeson** [awsdocs/amazon-elasticache-docs#40]
Referring to this page: https://github.com/awsdocs/amazon-elasticache-docs/blob/master/doc_source/redis/ElastiCache-Outposts.md

On Outposts, EBS capacity is a constrained resource. ElastiCache abstracts its EBS usage from users in the region but can't do the same on Outposts due to this constraint. This documentation page needs to tell customers how much EBS capacity ElastiCache nodes of each size consume so that customers can plan their Outpost cluster deployments without getting unanticipated EBS capacity exceptions.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
