### ISSUE TITLE
Document what "enhanced IO" means

### ISSUE THREAD

**Issue by MasonM** [awsdocs/amazon-elasticache-docs#53]
At https://github.com/awsdocs/amazon-elasticache-docs/blob/master/doc_source/redis/VersionManagement.md, it says:
> If you upgrade to engine version 5.0.3 or higher and the number of vCPUs is at least 4, enhanced IO triggers and you can expect to see increased EngineCPUUtilization and CPUUtilization.

But it doesn't explain what "enhanced IO" means, or why you would want this. I found this blog post, which discusses "enhanced I/O handling": https://aws.amazon.com/blogs/database/boosting-application-performance-and-reducing-costs-with-amazon-elasticache-for-redis/

Assuming that blog post is talking about the same thing, I'd be nice to incorporate that information into the documentation.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
