### ISSUE TITLE
Unable to configure ElastiCache for outsude access

### ISSUE THREAD

**Issue by anking** [awsdocs/amazon-elasticache-docs#61]
I tried to use this guide to get access to my ElastiCache cluster via the VPN:
https://github.com/awsdocs/amazon-elasticache-docs/blob/master/doc_source/redis/accessing-elasticache.md

And after creating all the certs and establishing VPN connection I was able to access the redis DB via telnet.

However I need to be able to access internes as well because my application loads it's configuration thru different resources.

Currently when I'm connected with VPN I do not have any internet access at all.

Guide says that to enable internet access i need to "Target VPC Subnet ID: Select one of the associated subnets with access to the Internet."
But it doesn't really explain how to do this. 

When first created(following the guide) the only subnet that belongs to that VPC takes the entire block of IP addresses so I cannot add an additional subnet and I also cannot associate a different VPC with the other subnet.
I also wasn't able to split this Elasticache subnet into two but maybe I'm not doing something right.

Would be nice to show an example of how this can be achieved.

Thanks!

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
