### ISSUE TITLE
Missing wget when performing yum install

### ISSUE THREAD

**Issue by BabooPan** [awsdocs/amazon-elasticache-docs#66]
Missing wget would cause the instruction fail to build the redis-cli for amazon linux 2

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
