### ISSUE TITLE
Outdated statement about resharding with cluster mode enabled

### ISSUE THREAD

**Issue by hwatts** [awsdocs/amazon-elasticache-docs#7]
In [redis/CacheNodes.NodeGroups.md](https://github.com/awsdocs/amazon-elasticache-docs/blob/master/doc_source/redis/CacheNodes.NodeGroups.md), there's the following statement, which caused us some confusion:

>> When you create a Redis (cluster mode enabled) cluster, you specify from 1 to 15 shards. Currently, however, unlike Redis (cluster mode disabled) clusters, once a Redis (cluster mode enabled) cluster is created, its structure cannot be altered in any way; you cannot add or delete nodes or shards. If you need to add or delete nodes, or change node types, you must create the cluster anew.

Is this still correct since it seems online resharding is now supported for Redis clusters, or am I misunderstanding the context here?

**Comment by krishna81m** [comment]
Cluster Mode Enabled - has conflicting documentation in the User Guide.
https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/redis-ug.pdf

> After a Redis (cluster mode enabled) cluster is created, its structure can't be altered in any way. You *can't add or delete nodes or shards*. If you need to add or delete nodes, or change node types, you must create the cluster again.
> ...
> 
> Replace any node in a Redis (cluster mode enabled) shard – To *replace the node in a cluster with no
> downtime, use online resharding*. First add a shard by scaling out, and then delete the shard with the
> node to be replaced by scaling in.
> To replace any node in a Redis (cluster mode enabled) cluster
> 1. Scale out: Add an additional shard with the same configuration as the existing shard with the node
> to be replaced. For more information, see Adding Shards with Online Resharding (p. 252).
>

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
